add gradlew file validation

diff --git a/.github/workflows/generate-lib.yaml b/.github/workflows/generate-lib.yaml
--- a/.github/workflows/generate-lib.yaml
+++ b/.github/workflows/generate-lib.yaml
@@ -36,6 +36,15 @@ jobs:
         run: |
           git clone "https://${{ github.repository_owner }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository_owner }}/${{ inputs.artifact-id }}"
 
+      - name: Verify and set executable permission for gradlew
+        run: |
+          cd ./${{ inputs.artifact-id }}
+          if [ ! -f ./gradlew ]; then
+            echo "gradlew file is missing"
+            exit 1
+          fi
+          chmod +x ./gradlew
+          
       - name: Change group-id and artifact-id
         run: |
           cd ./${{ inputs.artifact-id }}
